/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as CodeHunterRouteImport } from './routes/code-hunter'
import { Route as KingOfCheapRouteImport } from './routes/king-of-cheap'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as ApiApiKeysIndexRouteImport } from './routes/api/api-keys/index'
import { Route as ApiCodesIndexRouteImport } from './routes/api/codes/index'
import { Route as ApiProvidersIndexRouteImport } from './routes/api/providers/index'
import { Route as ApiProvidersIdRouteImport } from './routes/api/providers/$id'
import { Route as ApiProvidersKlingRouteImport } from './routes/api/providers/kling'
import { Route as ApiProvidersSummaryRouteImport } from './routes/api/providers/summary'
import { Route as ApiResearchHistoryRouteImport } from './routes/api/research/history'
import { Route as ApiResearchResetRouteImport } from './routes/api/research/reset'
import { Route as ApiResearchStatusRouteImport } from './routes/api/research/status'
import { Route as ApiResearchTriggerRouteImport } from './routes/api/research/trigger'
import { Route as ApiApiKeysIdIndexRouteImport } from './routes/api/api-keys/$id/index'
import { Route as ApiApiKeysIdActivateRouteImport } from './routes/api/api-keys/$id/activate'
import { Route as ApiApiKeysIdDeactivateRouteImport } from './routes/api/api-keys/$id/deactivate'
import { Route as ApiApiKeysByProviderProviderRouteImport } from './routes/api/api-keys/by-provider/$provider'
import { Route as ApiCodesResearchIndexRouteImport } from './routes/api/codes/research/index'
import { Route as ApiCodesResearchStatusRouteImport } from './routes/api/codes/research/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeHunterRoute = CodeHunterRouteImport.update({
  id: '/code-hunter',
  path: '/code-hunter',
  getParentRoute: () => rootRouteImport,
} as any)
const KingOfCheapRoute = KingOfCheapRouteImport.update({
  id: '/king-of-cheap',
  path: '/king-of-cheap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysIndexRoute = ApiApiKeysIndexRouteImport.update({
  id: '/api/api-keys/',
  path: '/api/api-keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodesIndexRoute = ApiCodesIndexRouteImport.update({
  id: '/api/codes/',
  path: '/api/codes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersIndexRoute = ApiProvidersIndexRouteImport.update({
  id: '/api/providers/',
  path: '/api/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersIdRoute = ApiProvidersIdRouteImport.update({
  id: '/api/providers/$id',
  path: '/api/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersKlingRoute = ApiProvidersKlingRouteImport.update({
  id: '/api/providers/kling',
  path: '/api/providers/kling',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersSummaryRoute = ApiProvidersSummaryRouteImport.update({
  id: '/api/providers/summary',
  path: '/api/providers/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchHistoryRoute = ApiResearchHistoryRouteImport.update({
  id: '/api/research/history',
  path: '/api/research/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchResetRoute = ApiResearchResetRouteImport.update({
  id: '/api/research/reset',
  path: '/api/research/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchStatusRoute = ApiResearchStatusRouteImport.update({
  id: '/api/research/status',
  path: '/api/research/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchTriggerRoute = ApiResearchTriggerRouteImport.update({
  id: '/api/research/trigger',
  path: '/api/research/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysIdIndexRoute = ApiApiKeysIdIndexRouteImport.update({
  id: '/api/api-keys/$id/',
  path: '/api/api-keys/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysIdActivateRoute = ApiApiKeysIdActivateRouteImport.update({
  id: '/api/api-keys/$id/activate',
  path: '/api/api-keys/$id/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysIdDeactivateRoute = ApiApiKeysIdDeactivateRouteImport.update({
  id: '/api/api-keys/$id/deactivate',
  path: '/api/api-keys/$id/deactivate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysByProviderProviderRoute =
  ApiApiKeysByProviderProviderRouteImport.update({
    id: '/api/api-keys/by-provider/$provider',
    path: '/api/api-keys/by-provider/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodesResearchIndexRoute = ApiCodesResearchIndexRouteImport.update({
  id: '/api/codes/research/',
  path: '/api/codes/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodesResearchStatusRoute = ApiCodesResearchStatusRouteImport.update({
  id: '/api/codes/research/status',
  path: '/api/codes/research/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/code-hunter': typeof CodeHunterRoute
  '/king-of-cheap': typeof KingOfCheapRoute
  '/research': typeof ResearchRoute
  '/api/health': typeof ApiHealthRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/api/providers/$id': typeof ApiProvidersIdRoute
  '/api/providers/kling': typeof ApiProvidersKlingRoute
  '/api/providers/summary': typeof ApiProvidersSummaryRoute
  '/api/research/history': typeof ApiResearchHistoryRoute
  '/api/research/reset': typeof ApiResearchResetRoute
  '/api/research/status': typeof ApiResearchStatusRoute
  '/api/research/trigger': typeof ApiResearchTriggerRoute
  '/api/api-keys/': typeof ApiApiKeysIndexRoute
  '/api/codes/': typeof ApiCodesIndexRoute
  '/api/providers/': typeof ApiProvidersIndexRoute
  '/api/api-keys/$id/activate': typeof ApiApiKeysIdActivateRoute
  '/api/api-keys/$id/deactivate': typeof ApiApiKeysIdDeactivateRoute
  '/api/api-keys/by-provider/$provider': typeof ApiApiKeysByProviderProviderRoute
  '/api/codes/research/status': typeof ApiCodesResearchStatusRoute
  '/api/api-keys/$id/': typeof ApiApiKeysIdIndexRoute
  '/api/codes/research/': typeof ApiCodesResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/code-hunter': typeof CodeHunterRoute
  '/king-of-cheap': typeof KingOfCheapRoute
  '/research': typeof ResearchRoute
  '/api/health': typeof ApiHealthRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/api/providers/$id': typeof ApiProvidersIdRoute
  '/api/providers/kling': typeof ApiProvidersKlingRoute
  '/api/providers/summary': typeof ApiProvidersSummaryRoute
  '/api/research/history': typeof ApiResearchHistoryRoute
  '/api/research/reset': typeof ApiResearchResetRoute
  '/api/research/status': typeof ApiResearchStatusRoute
  '/api/research/trigger': typeof ApiResearchTriggerRoute
  '/api/api-keys': typeof ApiApiKeysIndexRoute
  '/api/codes': typeof ApiCodesIndexRoute
  '/api/providers': typeof ApiProvidersIndexRoute
  '/api/api-keys/$id/activate': typeof ApiApiKeysIdActivateRoute
  '/api/api-keys/$id/deactivate': typeof ApiApiKeysIdDeactivateRoute
  '/api/api-keys/by-provider/$provider': typeof ApiApiKeysByProviderProviderRoute
  '/api/codes/research/status': typeof ApiCodesResearchStatusRoute
  '/api/api-keys/$id': typeof ApiApiKeysIdIndexRoute
  '/api/codes/research': typeof ApiCodesResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/code-hunter': typeof CodeHunterRoute
  '/king-of-cheap': typeof KingOfCheapRoute
  '/research': typeof ResearchRoute
  '/api/health': typeof ApiHealthRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/api/providers/$id': typeof ApiProvidersIdRoute
  '/api/providers/kling': typeof ApiProvidersKlingRoute
  '/api/providers/summary': typeof ApiProvidersSummaryRoute
  '/api/research/history': typeof ApiResearchHistoryRoute
  '/api/research/reset': typeof ApiResearchResetRoute
  '/api/research/status': typeof ApiResearchStatusRoute
  '/api/research/trigger': typeof ApiResearchTriggerRoute
  '/api/api-keys/': typeof ApiApiKeysIndexRoute
  '/api/codes/': typeof ApiCodesIndexRoute
  '/api/providers/': typeof ApiProvidersIndexRoute
  '/api/api-keys/$id/activate': typeof ApiApiKeysIdActivateRoute
  '/api/api-keys/$id/deactivate': typeof ApiApiKeysIdDeactivateRoute
  '/api/api-keys/by-provider/$provider': typeof ApiApiKeysByProviderProviderRoute
  '/api/codes/research/status': typeof ApiCodesResearchStatusRoute
  '/api/api-keys/$id/': typeof ApiApiKeysIdIndexRoute
  '/api/codes/research/': typeof ApiCodesResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/code-hunter'
    | '/king-of-cheap'
    | '/research'
    | '/api/health'
    | '/api/healthz'
    | '/providers/$id'
    | '/api/providers/$id'
    | '/api/providers/kling'
    | '/api/providers/summary'
    | '/api/research/history'
    | '/api/research/reset'
    | '/api/research/status'
    | '/api/research/trigger'
    | '/api/api-keys/'
    | '/api/codes/'
    | '/api/providers/'
    | '/api/api-keys/$id/activate'
    | '/api/api-keys/$id/deactivate'
    | '/api/api-keys/by-provider/$provider'
    | '/api/codes/research/status'
    | '/api/api-keys/$id/'
    | '/api/codes/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/code-hunter'
    | '/king-of-cheap'
    | '/research'
    | '/api/health'
    | '/api/healthz'
    | '/providers/$id'
    | '/api/providers/$id'
    | '/api/providers/kling'
    | '/api/providers/summary'
    | '/api/research/history'
    | '/api/research/reset'
    | '/api/research/status'
    | '/api/research/trigger'
    | '/api/api-keys'
    | '/api/codes'
    | '/api/providers'
    | '/api/api-keys/$id/activate'
    | '/api/api-keys/$id/deactivate'
    | '/api/api-keys/by-provider/$provider'
    | '/api/codes/research/status'
    | '/api/api-keys/$id'
    | '/api/codes/research'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/code-hunter'
    | '/king-of-cheap'
    | '/research'
    | '/api/health'
    | '/api/healthz'
    | '/providers/$id'
    | '/api/providers/$id'
    | '/api/providers/kling'
    | '/api/providers/summary'
    | '/api/research/history'
    | '/api/research/reset'
    | '/api/research/status'
    | '/api/research/trigger'
    | '/api/api-keys/'
    | '/api/codes/'
    | '/api/providers/'
    | '/api/api-keys/$id/activate'
    | '/api/api-keys/$id/deactivate'
    | '/api/api-keys/by-provider/$provider'
    | '/api/codes/research/status'
    | '/api/api-keys/$id/'
    | '/api/codes/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  CodeHunterRoute: typeof CodeHunterRoute
  KingOfCheapRoute: typeof KingOfCheapRoute
  ResearchRoute: typeof ResearchRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  ApiProvidersIdRoute: typeof ApiProvidersIdRoute
  ApiProvidersKlingRoute: typeof ApiProvidersKlingRoute
  ApiProvidersSummaryRoute: typeof ApiProvidersSummaryRoute
  ApiResearchHistoryRoute: typeof ApiResearchHistoryRoute
  ApiResearchResetRoute: typeof ApiResearchResetRoute
  ApiResearchStatusRoute: typeof ApiResearchStatusRoute
  ApiResearchTriggerRoute: typeof ApiResearchTriggerRoute
  ApiApiKeysIndexRoute: typeof ApiApiKeysIndexRoute
  ApiCodesIndexRoute: typeof ApiCodesIndexRoute
  ApiProvidersIndexRoute: typeof ApiProvidersIndexRoute
  ApiApiKeysIdActivateRoute: typeof ApiApiKeysIdActivateRoute
  ApiApiKeysIdDeactivateRoute: typeof ApiApiKeysIdDeactivateRoute
  ApiApiKeysByProviderProviderRoute: typeof ApiApiKeysByProviderProviderRoute
  ApiCodesResearchStatusRoute: typeof ApiCodesResearchStatusRoute
  ApiApiKeysIdIndexRoute: typeof ApiApiKeysIdIndexRoute
  ApiCodesResearchIndexRoute: typeof ApiCodesResearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-hunter': {
      id: '/code-hunter'
      path: '/code-hunter'
      fullPath: '/code-hunter'
      preLoaderRoute: typeof CodeHunterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/king-of-cheap': {
      id: '/king-of-cheap'
      path: '/king-of-cheap'
      fullPath: '/king-of-cheap'
      preLoaderRoute: typeof KingOfCheapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/': {
      id: '/api/api-keys/'
      path: '/api/api-keys'
      fullPath: '/api/api-keys/'
      preLoaderRoute: typeof ApiApiKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codes/': {
      id: '/api/codes/'
      path: '/api/codes'
      fullPath: '/api/codes/'
      preLoaderRoute: typeof ApiCodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/': {
      id: '/api/providers/'
      path: '/api/providers'
      fullPath: '/api/providers/'
      preLoaderRoute: typeof ApiProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/$id': {
      id: '/api/providers/$id'
      path: '/api/providers/$id'
      fullPath: '/api/providers/$id'
      preLoaderRoute: typeof ApiProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/kling': {
      id: '/api/providers/kling'
      path: '/api/providers/kling'
      fullPath: '/api/providers/kling'
      preLoaderRoute: typeof ApiProvidersKlingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/summary': {
      id: '/api/providers/summary'
      path: '/api/providers/summary'
      fullPath: '/api/providers/summary'
      preLoaderRoute: typeof ApiProvidersSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/history': {
      id: '/api/research/history'
      path: '/api/research/history'
      fullPath: '/api/research/history'
      preLoaderRoute: typeof ApiResearchHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/reset': {
      id: '/api/research/reset'
      path: '/api/research/reset'
      fullPath: '/api/research/reset'
      preLoaderRoute: typeof ApiResearchResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/status': {
      id: '/api/research/status'
      path: '/api/research/status'
      fullPath: '/api/research/status'
      preLoaderRoute: typeof ApiResearchStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/trigger': {
      id: '/api/research/trigger'
      path: '/api/research/trigger'
      fullPath: '/api/research/trigger'
      preLoaderRoute: typeof ApiResearchTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/$id/': {
      id: '/api/api-keys/$id/'
      path: '/api/api-keys/$id'
      fullPath: '/api/api-keys/$id/'
      preLoaderRoute: typeof ApiApiKeysIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/$id/activate': {
      id: '/api/api-keys/$id/activate'
      path: '/api/api-keys/$id/activate'
      fullPath: '/api/api-keys/$id/activate'
      preLoaderRoute: typeof ApiApiKeysIdActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/$id/deactivate': {
      id: '/api/api-keys/$id/deactivate'
      path: '/api/api-keys/$id/deactivate'
      fullPath: '/api/api-keys/$id/deactivate'
      preLoaderRoute: typeof ApiApiKeysIdDeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/by-provider/$provider': {
      id: '/api/api-keys/by-provider/$provider'
      path: '/api/api-keys/by-provider/$provider'
      fullPath: '/api/api-keys/by-provider/$provider'
      preLoaderRoute: typeof ApiApiKeysByProviderProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codes/research/': {
      id: '/api/codes/research/'
      path: '/api/codes/research'
      fullPath: '/api/codes/research/'
      preLoaderRoute: typeof ApiCodesResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codes/research/status': {
      id: '/api/codes/research/status'
      path: '/api/codes/research/status'
      fullPath: '/api/codes/research/status'
      preLoaderRoute: typeof ApiCodesResearchStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  CodeHunterRoute: CodeHunterRoute,
  KingOfCheapRoute: KingOfCheapRoute,
  ResearchRoute: ResearchRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  ApiProvidersIdRoute: ApiProvidersIdRoute,
  ApiProvidersKlingRoute: ApiProvidersKlingRoute,
  ApiProvidersSummaryRoute: ApiProvidersSummaryRoute,
  ApiResearchHistoryRoute: ApiResearchHistoryRoute,
  ApiResearchResetRoute: ApiResearchResetRoute,
  ApiResearchStatusRoute: ApiResearchStatusRoute,
  ApiResearchTriggerRoute: ApiResearchTriggerRoute,
  ApiApiKeysIndexRoute: ApiApiKeysIndexRoute,
  ApiCodesIndexRoute: ApiCodesIndexRoute,
  ApiProvidersIndexRoute: ApiProvidersIndexRoute,
  ApiApiKeysIdActivateRoute: ApiApiKeysIdActivateRoute,
  ApiApiKeysIdDeactivateRoute: ApiApiKeysIdDeactivateRoute,
  ApiApiKeysByProviderProviderRoute: ApiApiKeysByProviderProviderRoute,
  ApiCodesResearchStatusRoute: ApiCodesResearchStatusRoute,
  ApiApiKeysIdIndexRoute: ApiApiKeysIdIndexRoute,
  ApiCodesResearchIndexRoute: ApiCodesResearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
